name: solar-system-workflow
on: 
  push: 
    branches: 
      - main
      - 'feature/*'
  workflow_dispatch:
jobs:
  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install dependencies
        run: npm install
        
      - name: run unit test cases
        run: npm test
